version: '3.9'

services:
  bot:
    container_name: bot
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8005:8005"
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - ./conf/.env
    volumes:
      - .:/code
    networks:
      - battleship_backend_battleship-network

networks:
  battleship_backend_battleship-network:
    external: true